### ISSUE TITLE
Bug report: Gantt view not available to manager (Moved)

### ISSUE THREAD

**Issue by NoodleBB** [kanboard/plugin-gantt#11]
Moved from "https://github.com/kanboard/kanboard/issues/3146"

### Actual behaviour

A user with **manager** role in a project is unable to switch to the Gantt chart. The button for the Gantt chart view is gone.

### Expected behaviour

A user with **manager** role, must be able to see the gantt chart. Because it's **the manager**. So there should be the Gantt button.

### Steps to reproduce

1. Create a new project.
2. Create some tasks with dates.
3. Create a new user with **manager** role in that a project. 
4. Long out and login as the created user
5. Open the project.
6. Try to switch to the gantt chart. - It's impossible, because the button is missing.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.40
- Database type and version: sqlite 3.8.10.2
- PHP version: 5.6.21
- OS: Linux 2.6.32-642.6.2.el6.x86_64
- Browser/s: Safari, Chrome, Firefox.

**Comment by Minyun** [comment]
I see that this is closed. No matter what role I assign to the user (Admin, Manager, User, Project Manager, Project Member, Project Viewer) I still do not see the Gantt Chart available. Is there a fix to this yet? I have looked at the referenced issue but I see no resolution.

**Comment by asmwarrior** [comment]
I don't see this issue with the following settings:
```
Application version: 1.0.45
PHP version: 5.6.30
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite 
Gantt plugin: Version: 1.0.2 (the latest git master head)
```

**Comment by defcon1702** [comment]
You can solve the problem in the project settings.
You have to give the team members the userrole "project manager" then everybody see the GANT.

**Comment by NoodleBB** [comment]
But not all team members should be project managers.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
