### ISSUE TITLE
Moving to one day, store one day before at 22:00

### ISSUE THREAD

**Issue by devbieres** [kanboard/plugin-gantt#13]
**Please, do not create duplicate issues**

### Actual behaviour
When moving a tack in Gantt to a date, after reloading the task is saved the day before at 22:00.

### Expected behaviour
When moving to a date in Gantt, the start date of the taks is the selected date.

### Steps to reproduce

- Move a task in GanttProject
- Reload page
- Task is one day before expected

### Configuration

- Plugin version: latest
- Kanboard version: 1.0.35 / 1.0.45
- Database type and version: File
- PHP version: 5.6.0
- OS: Windows
- Browser: Firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
