### ISSUE TITLE
PDF EXPORT GANTT

### ISSUE THREAD

**Issue by Richard76000** [kanboard/plugin-gantt#14]
PDF EXPORT GANTT please

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
