### ISSUE TITLE
Sorting by date, tasks starting at the same time but due sooner are not at top

### ISSUE THREAD

**Issue by rpfries** [kanboard/plugin-gantt#16]
I have two tasks.

Both have the same start date.
One ends Sept 29
One ends Sept 22

### Actual behaviour
The task ending Sept 29 shows first, then the one ending sooner.
![capture](https://user-images.githubusercontent.com/32111742/30615226-3b8af156-9d5c-11e7-96b3-d6b4ba54d5af.JPG)

### Expected behaviour
The task ending sooner should show first, as it's due first

- Plugin version: 1.0.2
- Kanboard version: 1.0.4.6
- Database type and version: sqlite 3.6.20
- PHP version: 5.3.3
- OS: RHEL 6.9
- Browser: IE

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
