### ISSUE TITLE
Use date_completed as end if set

### ISSUE THREAD

**Issue by kent1D** [kanboard/plugin-gantt#17]
**Please, do not create duplicate issues**

### Actual behaviour

Actually the Gantt plugin only take `date_started` for start date (normal) and `date_due` for end date. It doesn't take care of `date_completed` which should be if used the real end date of a task.

Moreover the translation in french is talking about "end date" and not "due date"

### Expected behaviour

If set, use `date_completed` as end date

### Configuration

- Plugin version: 1.0.2

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
