### ISSUE TITLE
Gantt Chart View shows nothing if I switch to Chinese language, but it shows OK under English language

### ISSUE THREAD

**Issue by asmwarrior** [kanboard/plugin-gantt#2]
I have the latest Kanboard(1.0.42) installed, and with the latest gantt installed. I can see the gantt chart if I set the user profile language as English. But If I switch the language to Chinese, then I can still see the gantt tabs, but the gantt chart is empty.  Any ideas how to fix this issue? Thanks.

**Comment by asmwarrior** [comment]
Here is the screen shot of English language and Chinese language, you see when in Chinese language, it shows nothing.
![bad](https://cloud.githubusercontent.com/assets/561818/25222793/20b032b6-25ec-11e7-81a7-5e9cbb4cb16d.png)
![good](https://cloud.githubusercontent.com/assets/561818/25222794/20b0d270-25ec-11e7-8517-a178d50b6cbb.png)

**Comment by asmwarrior** [comment]
I just tested an old version of kanboard, It looks like this bug does not happens in the 1.0.41 version of kanboard, which the gantt is not separated from the kanboard code base.  The 1.0.42 is the first version which gantt plugin is removed from the main kanboard code base, and becomes a separated plugin.

**Comment by asmwarrior** [comment]
I just test Kanboard (kanboard-1.0.45.zip) and with gantt plugin(8217dc1) latest master version, I don't see this issue now. I'm testing under Windows7 system, not sure it works OK under other system.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
