### ISSUE TITLE
Missing comma in german translation

### ISSUE THREAD

**Issue by mkluge** [kanboard/plugin-gantt#26]
The site does not load and PHP says:

PHP Parse error: syntax error, unexpected ''Chat id of group chat with bo' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /volume1/web/kanboard/plugins/Telegram/Locale/de_DE/translations.php on line 8

There is a comma missing in kanboard/plugins/Telegram/Locale/de_DE/translations.php. Found in todays v1.2.4. and the current plugin version.

**Comment by mkluge** [comment]
Yes, and there is a bug in the german translation file of the Telegram plugin for kanboard.

**Comment by fguillot** [comment]
This is the wrong bug tracker, see https://github.com/manuvarkey/kanboard-plugin-telegram/issues and https://github.com/manuvarkey/kanboard-plugin-telegram/commit/10b3e720c6bf7a967e35e3fee99e97f0dc51562a#diff-53801ca1a15bea82e444e19d94820d2e
