### ISSUE TITLE
Gantt plugin: Class 'Kanboard\Formatter\TaskGanttFormatter' not found

### ISSUE THREAD

**Issue by hbrodbeck** [kanboard/plugin-gantt#3]
After installing the Gantt plugin and selecting the Gantt View the following error is shown:

Fatal error: Class 'Kanboard\Formatter\TaskGanttFormatter' not found in /home/brodbeck/brodbeck.com.br/kanboard/plugins/Milestone/Formatter/TaskGanttLinkAwareFormatter.php on line 14

Kanboard version 1.0.43 and Gantt plugin version 1.01.

After unistalling the plugin and reinstalling it the error didn't show again.

**Comment by fguillot** [comment]
The error seems to come from the plugin Milestone, perhaps you could contact its author.

**Comment by fguillot** [comment]
A patch has been proposed to the plugin author: https://github.com/oliviermaridat/kanboard-milestone-plugin/pull/11

**Comment by fguillot** [comment]
The Milestone plugin has been updated.
