### ISSUE TITLE
problem with viewing right

### ISSUE THREAD

**Issue by Danyt83** [kanboard/plugin-gantt#30]
a user with a viewing right on a project can change the dates with the gant plugin

- Plugin version: 1.0.4
- Kanboard version: 1.2.5
- OS: debian9
- Browser: all

**Comment by creecros** [comment]
That will prevent a viewer from saving anything in Gantt View.

**Comment by creecros** [comment]
Here was the culprit:
kanboard/plugin-gantt#11 followed by the merge kanboard/plugin-gantt#23
