### ISSUE TITLE
Gantt view button not shown

### ISSUE THREAD

**Issue by n1trux** [kanboard/plugin-gantt#5]
I unpacked the plugin into my installation's plugin/Gantt folder. It shows as enabled in the plugin manager but there's no Gantt button in the overview. I'm the project owner and the Calendar plugin (for example) works well.

This also doesn't seem to be in the official plugin directory.

**Comment by robsonpiere** [comment]
I checked and it looks like the button is only showing up for admin users.
Changing the profile of a user the button appears or not.

**Comment by steve-ks** [comment]
Hi there,
we also detected a problem with the Gantt view. As soon as we set a project as global (giving everybody access to it) only the project creator or admin users have access to the gantt view (also seeing the button). Other users (indepented of their previous project role) cannot see the gantt button. 

Adding the Gantt view to all people or another project configuration for the gantt plugin would be helpful.

**Comment by Minyun** [comment]
No matter what role I assign to the user (Admin, Manager, User, Project Manager, Project Member, Project Viewer) I still do not see the Gantt Chart available. Is there a fix/workaround for this yet? I have tried everything...

**Comment by chlarsen** [comment]
There seems to be a general problem with the calendar and Gantt chart visibility. The buttons show, but the respective calendar and Gantt chart views do not, if I am admin or manager. Users cannot see the Gantt chart button. This renders the whole exercise a bit useless for teamwork. The system does not throw any error messages, so it is difficult to debug this. Any thoughts?

**Comment by asmwarrior** [comment]
See here for my workaround about this issue: [Gant Chart only visible for Project Manager · Issue #1667 · kanboard/kanboard](https://github.com/kanboard/kanboard/issues/1667)

**Comment by chlarsen** [comment]
Thank you, much appreciated!
Chris

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
