### ISSUE TITLE
chrome ram limit reached - moved from kanboard/issues/3101

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/plugin-gantt#9]
Actual behaviour

Our Kanboard has +400 open tasks scattered over a few swimlanes and columns.
When I open the Gantt chart view for all tasks, chrome reaches it's ram limit and won't load the chart.

Expected behaviour

The Gantt chart should be displayed.

Steps to reproduce

create lots of tasks
try to view the gantt chart.
Configuration

Application version: 1.0.38
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

I can check if it is still relevant on tuesday.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
